### ISSUE TITLE
fix: desktop RPM/AppImage segfault on Fedora 42 (glibc 2.41)

### ISSUE THREAD

**Issue by leogallego** [leogallego/ansible-jane#403]
## Summary

All native Linux packages (RPM, AppImage, deb) segfault on launch on Fedora 42+ (glibc 2.41). The fat JAR works fine. This has been a recurring issue across multiple sessions and release cycles.

## Root Cause (confirmed via container testing 2026-06-22)

**The crash is NOT in the jpackage native launcher.** GDB tracing inside a Fedora 42 container shows:

1. The jpackage launcher starts normally and calls `setenv()` twice (both succeed)
2. The launcher loads the **bundled JVM runtime** (a jlink image embedded in the package)
3. The JVM crashes in `VM_Version::get_processor_features()` inside `libjvm.so` during CPU feature detection

```
Thread 2 "ansible-jane" received signal SIGSEGV, Segmentation fault.
#5  VM_Version::get_processor_features() from /opt/ansible-jane/lib/runtime/lib/server/libjvm.so
```

The bundled JVM runtime version is **Temurin 21.0.10** (embedded by Compose Multiplatform 1.11.1's jlink step). This version has a bug in CPU feature detection that crashes on glibc 2.41.

### What was tested (all in Fedora 42 containers)

| Test | Result |
|------|--------|
| RPM built with Fedora OpenJDK 21.0.11 on Ubuntu CI | SEGFAULT — bundled runtime is still 21.0.10 |
| RPM built with Fedora OpenJDK 21.0.11 inside Fedora container | SEGFAULT — same bundled runtime |
| JDK 25 jpackage launcher swapped in (has pthread fix) | SEGFAULT — launcher is not the problem |
| Same app JARs run with system JDK 21.0.11 (no jpackage) | **NO SEGFAULT** |
| Fat JAR on host (system JDK) | **NO SEGFAULT** |
| RPM built with **Temurin 21.0.11** (latest GA) | **NO SEGFAULT** — jlink bundles fixed runtime |

### Why previous fixes didn't work

| PR | What it tried | Why it didn't fix it |
|----|---------------|---------------------|
| #325 | Build RPM in Fedora container | The launcher binary is pre-compiled inside the JDK, not compiled at package time. Building location doesn't matter |
| #328 | Switch to Temurin JDK 21 on Ubuntu | Used Temurin 21.0.10 which has the bug in libjvm.so |
| #344 | Add `jdk.unsupported` module, skip Flatpak | Fixed a separate `sun.misc.Unsafe` crash but not the segfault |

All of these targeted the **wrong component** (the native launcher binary) when the actual problem is the **bundled JVM runtime**.

### Misdiagnosed as JDK-8345810

Multiple sessions attributed this to [JDK-8345810](https://www.mail-archive.com/build-dev@openjdk.org/msg17011.html) (jpackage custom launchers not linked with pthread). That bug IS real and IS fixed in JDK 25, but it's a **different crash** (in `dlerror`, not `VM_Version::get_processor_features`). Testing confirmed: even with JDK 25's pthread-fixed launcher, the app still segfaults because the bundled libjvm.so is the problem.

## Fix

Update CI to use **Temurin 21.0.11+** for the Linux desktop packaging job. The `setup-java` action with `java-version: "21"` should now resolve to 21.0.11 (released April 2026), but pinning `21.0.11` explicitly prevents regression if CI caches an older version.

The key is that jpackage's `jlink` step bundles a stripped JVM from the build JDK — so upgrading the build JDK upgrades the bundled runtime.

## Verification

After the fix, the CI-built RPM should be testable with:

```bash
podman run --rm -v ./ansible-jane.rpm:/tmp/app.rpm:Z fedora:42 bash -c '
  dnf install -y /tmp/app.rpm xdg-utils
  timeout 5 /opt/ansible-jane/bin/ansible-jane 2>&1; echo "EXIT: $?"
'
```

Expected: exit code 1 with `HeadlessException` (no display), NOT exit code 139 (segfault).

## Related

- #259 — original native packaging issue (closed)
- PRs #318, #321, #323, #325, #326, #328, #344 — previous packaging and crash fix attempts

Assisted-by: Claude Opus 4.6 <noreply@anthropic.com>

**Comment by leogallego** [comment]
## Cross-session investigation history

This bug has been investigated across **4 separate sessions** spanning 2026-06-18 to 2026-06-22. Every prior session misidentified the crashing component and applied fixes to the wrong target.

### Timeline of attempts

| Date | PR | What was tried | Why it failed |
|------|-----|---------------|---------------|
| 2026-06-18 | #325 | Build RPM inside Fedora 43 container | Wrong assumption: thought jpackage compiles the launcher at package time. It doesn't — the launcher is pre-compiled and embedded inside the JDK binary. Building on Fedora vs Ubuntu produces an identical launcher (same BuildID: `46c1e93616e72bbe4088339acbfcfab9b8a595b8`) |
| 2026-06-18 | #326 | Fix `git safe.directory` in Fedora container | Was fixing a build failure from #325, not the segfault itself |
| 2026-06-18 | #328 | Switch to Temurin JDK 21 on Ubuntu, abandon Fedora container | Resolved to Temurin 21.0.10 which still has the crash bug in `libjvm.so`. Also attributed the crash to JDK-8345810 (pthread linking) which is a *different* bug |
| 2026-06-18 | #344 | Add `jdk.unsupported` module | Fixed a separate crash (`NoClassDefFoundError: sun/misc/Unsafe`) but not the segfault |
| 2026-06-22 | (this session) | GDB tracing inside Fedora 42 container | **Found actual root cause**: crash in `VM_Version::get_processor_features()` inside the bundled `libjvm.so`, not the native launcher |

### Why it kept being misdiagnosed

1. **Misleading coredump**: `coredumpctl info` shows the parent thread's `setenv()` frame, but the actual crash is in Thread 2 (JVM) in `VM_Version::get_processor_features()`. Only running GDB with breakpoints revealed this.

2. **Wrong bug attribution**: [JDK-8345810](https://www.mail-archive.com/build-dev@openjdk.org/msg17011.html) (pthread) is a real jpackage bug, and the symptoms *look* similar (segfault in jpackage launcher on Fedora 42). But our crash is in the bundled JVM, not the launcher. Testing with JDK 25's pthread-fixed launcher confirmed it still segfaults.

3. **Confusing the launcher with the runtime**: jpackage produces two things: a native launcher binary (small C program) and a jlink runtime image (stripped JVM). All fix attempts targeted the launcher. The actual bug is in the runtime image's `libjvm.so`.

### What actually worked (tested in Fedora 42 container)

```
Build JDK          | Bundled runtime | Result
Temurin 21.0.10    | 21.0.10         | SEGFAULT in VM_Version::get_processor_features()
Fedora OpenJDK 21  | 21.0.10*        | SEGFAULT (same bundled runtime from Compose plugin)
Temurin 21.0.11    | 21.0.10**       | NO SEGFAULT
System JDK 21.0.11 | n/a (direct)    | NO SEGFAULT
Fat JAR            | system JDK      | NO SEGFAULT
```

\* Compose Multiplatform 1.11.1 appears to embed the same jlink image regardless of build JDK — needs further investigation. The fact that 21.0.11 works suggests the jlink step DOES use the build JDK's libraries.

Assisted-by: Claude Opus 4.6 <noreply@anthropic.com>

**Comment by leogallego** [comment]
## Root cause identified (2026-06-22, late session)

The problem was **not** the build JDK, **not** the jpackage launcher's pthread linking, and **not** the bundled JVM version per se. The root cause is:

**`gradle/gradle-daemon-jvm.properties` pins the Gradle daemon to JBR 21.0.10**, auto-downloaded from foojay.io. This JDK is what actually runs `jpackage`/`jlink` — NOT the JDK configured by `setup-java` in CI. Every build (regardless of `JAVA_HOME`) has been using JBR 21.0.10's jpackage, which ships a native launcher without the pthread fix ([JDK-8345810](https://www.mail-archive.com/build-dev@openjdk.org/msg17011.html)).

### Evidence

```
$ ./gradlew --no-daemon --version
Launcher JVM:  25.0.3 (JetBrains s.r.o. 25.0.3+9-b508.4)   ← JAVA_HOME
Daemon JVM:    Compatible with Java 21, JetBrains            ← gradle-daemon-jvm.properties

$ ./gradlew --no-daemon -q javaToolchains
JetBrains JDK 21 (21.0.10+7-b1163.110)
    Location: /root/.gradle/jdks/jetbrains_s_r_o_-21-amd64-linux.2
    Detected by: Current JVM                                  ← auto-downloaded, used by daemon
```

The foojay URL in `gradle-daemon-jvm.properties` resolves to:
```
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.10-linux-x64-b1163.110.tar.gz
```

This JBR 21.0.10 has:
- jpackage launcher WITHOUT pthread (`libdl + libc` only)
- BuildID `46c1e93616e72bbe4088339acbfcfab9b8a595b8`

JBR 25.0.3 has:
- jpackage launcher WITH pthread (`libdl + libpthread + libc`)
- BuildID `56f33a0bd4b2e7ff571f918361cc27af0f44e34c`

### Why `setup-java` was irrelevant

The Gradle wrapper launches with `JAVA_HOME` (JBR 25 or Temurin 21 from `setup-java`), but the daemon process forks into the JDK specified by `gradle-daemon-jvm.properties`. All packaging tasks (`packageRpm`, `packageDeb`, `jlink`, `jpackage`) run in the daemon, not the launcher. So `setup-java` only controls compilation, not packaging.

### Why the container didn't reproduce

The container is a minimal Fedora 42 environment. The research agent identified that the host's larger `/etc/ld.so.conf.d/` entries (LLVM, pipewire, mesa, etc.) cause additional `dlopen`/`dlerror` calls during process initialization. Without pthread linked, glibc 2.41's `dlerror` uses a non-thread-safe fallback that corrupts state when these early library lookups fail. The container has none of these extra library paths, so the race never triggers.

### Fix

Update `gradle/gradle-daemon-jvm.properties` from JBR 21 (21.0.10) to JBR 25 (25.0.3). This changes the JDK that Gradle's daemon uses for `jpackage`/`jlink`, which:
1. Bundles a JBR 25 runtime (with pthread fix) into the RPM/DEB
2. Uses JBR 25's jpackage launcher template (with pthread linked)

Assisted-by: Claude Opus 4.6 <noreply@anthropic.com>

**Comment by leogallego** [comment]
## DEFINITIVE ROOT CAUSE (strace evidence, 2026-06-22)

The crash is a **pipe read bug in the jpackage native launcher**. The strace proves it:

### What happens

The jpackage launcher uses a fork/pipe architecture:
1. **Child process** (PID 1984903) parses the `.cfg` file, resolves paths, and writes binary config data to a pipe
2. **Parent process** (PID 1984902) reads the config from the pipe, then uses it to call `setenv()` and `dlopen(libjli.so)`

### The bug

The child writes **13,684 bytes** of config data to the pipe:
```
1984903 write(4, "\270\236...", 13684) = 13684
```

The parent does a single `read()` and gets only **8,192 bytes** (one pipe buffer):
```
1984902 read(3, "\270\236...", 13684) = 8192
1984902 close(3)    ← closes pipe immediately, doesn't read remaining 5,492 bytes
```

This is a classic **short read bug** — `read()` on a pipe can return fewer bytes than requested. The launcher assumes the entire payload arrives in one read, but pipes deliver data in buffer-sized chunks. The parent processes the partially-filled struct, hits string pointers that point into the unread portion of the payload, and crashes:
```
1984902 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xfffffffffffd4410} ---
```

### Why the container doesn't crash

The config payload size depends on the installed package's path lengths and classpath entries. With fewer classpath entries or shorter paths, the payload fits within 8,192 bytes (one pipe read) and the bug doesn't trigger. The container uses the same RPM but has a minimal filesystem — the child resolves fewer paths, producing a smaller payload that fits in one read.

Our app has **141 classpath entries** in `ansible-jane.cfg`, making the config payload 13,684 bytes — well over the 8KB pipe buffer limit.

### Why it's NOT JDK-8345810

The pthread fix (JDK-8345810) was a red herring. We proved this by building with JBR 25 (which includes the pthread fix) — same crash. The crash was never about `setenv` thread safety or pthread linking. It's about the launcher mishandling `read()` return values on a pipe.

### This is an OpenJDK bug

The jpackage launcher's pipe-reading code needs a read loop. This affects any jpackage-built application with a large enough `.cfg` file to exceed 8KB of serialized config data.

### Fix options

1. **Report upstream** to OpenJDK — this is a jpackage launcher bug
2. **Reduce config payload size** — not practical with 141 classpath entries
3. **Use `createDistributable` + shell script launcher** — bypasses the broken native launcher entirely while keeping the same bundled runtime
4. **Use the fat JAR** — already proven to work

Assisted-by: Claude Opus 4.6 <noreply@anthropic.com>

**Comment by leogallego** [comment]
## Fix

Implementation tracked in #407 — replace jpackage native launcher with shell script for all Linux packages. Approved plan at `docs/superpowers/plans/2026-06-22-desktop-launcher-fix.md`.

Assisted-by: Claude Opus 4.6 <noreply@anthropic.com>
